version: "3"

services:
  flance-app:
    build: ./
    container_name: flance-app
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - ZOOM_LINK=${ZOOM_LINK}
      - FRONTEND_URL=${FRONTEND_URL}
      - BLOCKCHAIN_URL=${BLOCKCHAIN_URL}
